### ISSUE TITLE
师傅您好，请教您一个问题

### ISSUE THREAD

**Issue by mcyydscc** [Holmose/CTFD_diy#1]
师傅你好，请教您一个问题
就是在用户启动 动态靶机之后，如果立马点进靶机地址，因为靶机还没有完全形成，所以会是502界面，需要怎么去修改这个页面，变成让用户等待的html
![image](https://user-images.githubusercontent.com/90653809/188271629-4d304d83-04a2-44ec-9b88-4d320ea0e596.png)

**Comment by Holmose** [comment]
需要下载frp的服务端程序源码来改，改了之后自行编译

**Comment by mcyydscc** [comment]
> 需要下载frp的服务端程序源码来改，改了之后自行编译

好的，谢谢师傅
